
- name: Invoice
  type: object
  path: $.lineItems[*]
  labels:
    environment: $.sku
    date: $.created
  values:
    totalPriceCents: $.totalPriceCents

- name: ClusterValue
  type: object
  path: $.lineItems[*]?(@.clusterName != "")
  labels:
    cluster: $.clusterName
    environment: $.sku
    date: $.created
  values:
    totalPriceCents: $.totalPriceCents

- name: id
  path: $.creditsCents
  labels:
    id: $.id
    endDate: $.endDate
